# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmPractice' do
  pod 'SnapKit', '~>5.6.0'
  pod 'Realm', '~>10.26.0', :modular_headers => true
  pod 'RealmSwift', '~>10', :modular_headers => true
  pod 'Moya', '~> 15.0'
end
